Develop
oracle-quickstart/oci-hpc-runbook-starccm pull request #2
Opened 2021-11-23 16:56 UTC by harrisondvoor

Updated stack

2021-12-08 16:22 UTC, lfeldman requested changes

2021-12-08 16:22 UTC, lfeldman commented on data.tf
> +resource "random_pet" "name" {
Please merge `data.tf `file and `datasources.tf `and return with new commit. Now when I am trying to test the code I am facing the issue:

![image](https://user-images.githubusercontent.com/19390609/143196520-75e7ffa5-50d4-4cb9-8f13-0810e36a4512.png)

2021-12-13 14:29 UTC, closed without merging

2022-01-03 13:21 UTC, glorialee820 commented on data.tf
> +resource "random_pet" "name" {
datasources.tf should be removed, data.tf is the correct file

2022-01-03 13:41 UTC, lfeldman commented on data.tf
> +resource "random_pet" "name" {
@glorialee820 that is fine, so please remove it in your local repo when you are in develop branch and then use `git rm` command to include that in the future commit. Next, you should create this commit (`git commit`) and push the change into this PR (`git push`). This is the way to continue the conversation here and respond to my change request after my review.